//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LADA Control Module.rc
//
#define IDCONTINUE                      8
#define IDTRYAGAIN                      9
#define IDD_ABOUTBOX                    100
#define IDR_GRAPHBUTTONFORM_TMPL        100
#define IDD_LADACONTROLMODULE_FORM      101
#define IDS_DATA_TRANSFER               101
#define IDD_GRAPHBUTTONFORM_FORM        102
#define IDS_GRAPH                       102
#define IDS_CAMERAS                     103
#define RENAME_LOCATION                 104
#define IDS_SYSTEM_CHECK                104
#define IDS_CHANGE_LANGUAGE             105
#define IDS_MAN_SAMPLE                  106
#define PROGRESS_DIALOG                 107
#define IDS_SYSTEM_CONTROLS             107
#define IDS_HELP                        108
#define IDS_NEXTBUTTON                  109
#define IDS_STEXT1                      110
#define IDS_STEXT2                      111
#define IDS_STEXT3                      112
#define IDS_STEXT4                      113
#define IDS_STEXT5                      114
#define IDS_STEXT6                      115
#define IDS_STRING116                   116
#define IDS_SBUTTON1                    117
#define IDS_SBUTTON2                    118
#define IDS_SBUTTON3                    119
#define IDC_HELPTEXT1                   120
#define IDS_SBUTTON4                    120
#define IDC_HELPTEXT2                   121
#define IDS_SBUTTON5                    121
#define IDC_HELPTEXT3                   122
#define IDS_SBUTTON6                    122
#define IDC_HELPTEXT4                   123
#define IDS_SBUTTON7                    123
#define IDC_HELPTEXT5                   124
#define IDS_STRING124                   124
#define IDC_HELPTEXT6                   125
#define IDS_STITLE                      125
#define IDC_HELPTEXT7                   126
#define IDC_WELCOMETEXT                 127
#define IDS_STRING127                   127
#define IDR_MAINFRAME                   128
#define ID_SETUP                        128
#define IDR_LADATYPE                    129
#define MONITOR_DIALOG                  129
#define ID_CHECK_OUT                    129
#define ID_WET_UP                       130
#define IDD_LANGUAGE                    130
#define IDD_CHOOSE_TIME                 131
#define ID_NORMAL                       131
#define ID_DIAGNOSTICS                  132
#define IDD_CANCELTRYCONTINUE           132
#define IDD_NEW_PROJECT                 133
#define IDB_HOTTOOLBAR                  133
#define ID_CHANGE_LANGUAGE              133
#define IDB_COLDTOOLBAR                 134
#define ID_EXIT                         134
#define IDD_OK                          134
#define IDC_TEMP_FILEVIEW               135
#define IDD_RETRYCANCEL                 135
#define IDD_YESNO                       136
#define UPDATE_GRAPH_TIMER              137
#define FINAL_STORAGE_TIMER             138
#define IDB_NCONNECTED                  140
#define IDB_CONNECTED                   141
#define GET_IL_DATA                     143
#define SAVE_IL_DATA                    144
#define IDB_HOTTOOR                     145
#define INITIAL_TIMER                   145
#define WETUP_TIMER                     146
#define UPDATE_VIEW_TIMER               147
#define DESTROY_TIMERS                  148
#define UPDATE_CR10_TIME                149
#define IDC_FIRST_CHECKBOX              150
#define IDD_GRAPH_PROPERTIES            150
#define FIRST_IL_TIMER                  150
#define IDD_CAMERADIALOG_DIALOG         151
#define IDC_MANUAL_CTRL                 155
#define IDB_PROGRAMBMP                  156
#define INPUT_LOCATION_TIMER            156
#define IDB_CHECKBOXES                  157
#define CAMERA_TIMER                    157
#define IDD_EDITLOCATION                158
#define IDD_DATA_TRANSFER               164
#define LAST_IL_TIMER                   170
#define IDD_SELECTICON                  178
#define IDD_MINMAX                      180
#define IDD_MANUALTEST                  181
#define IDD_MANUALTEST2                 181
#define IDD_VERIFY                      182
#define IDD_TEST                        183
#define IDD_WETUPSETTINGS               184
#define IDD_VIEWHISTORY                 185
#define IDB_MANMODE                     186
#define IDD_DISPLAY                     190
#define IDB_AUTOMODE                    192
#define IDD_DIALOG1                     193
#define IDD_FLAG                        193
#define IDD_DIALOG2                     195
#define IDD_COLLECTION                  195
#define IDD_CR10_FUNCTIONS              196
#define IDD_CAMERA                      197
#define IDD_DIALOG3                     198
#define IDD_MANUAL_CONTROL              199
#define IDC_LAST_CHECKBOX               200
#define FIRST_IL_SAVE_TIMER             200
#define IDD_IL_PROPERTIES               200
#define IDC_FIRSTNUMBERBOX              201
#define IDB_W_SETUP                     201
#define IDD_PICTURE_STATUS              202
#define IDD_REPLACE_GRAPH               203
#define IDD_DIALOG4                     204
#define IDD_IMPORT_FSL                  205
#define IDD_DIALOG5                     206
#define IDD_CALIBRATION                 207
#define IDD_CALIBRATE2                  208
#define IDD_PARAM_MENU                  209
#define IDD_SET_FREQUENCY               210
#define IDD_ASSIGN_UNITS                212
#define IDD_ENTER_UNITS                 213
#define IDD_LADATEST2                   214
#define IDD_MEASUREWATER                215
#define IDD_PUMP_CHECK_1                216
#define LAST_IL_SAVE_TIMER              220
#define TAKE_PICTURE_1                  300
#define TAKE_PICTURE_2                  301
#define IDC_FREQUENCY                   1000
#define IDC_DIAGLIST                    1000
#define ID_UPDATE                       1000
#define IDC_RESOLUTION                  1001
#define IDC_FANP                        1001
#define IDC_TIMELEFT                    1001
#define IDC_CR10_M_LEVEL                1001
#define IDC_AUTOWRAP                    1002
#define IDC_SELECT                      1002
#define IDC_LIGHTP                      1002
#define IDC_WATERPUMPED                 1002
#define IDC_CR10_FAN_TIME               1002
#define IDC_MOISTURE_READING            1002
#define IDC_FILEBOX                     1003
#define IDC_PROPERTIES                  1003
#define IDC_WATERP                      1003
#define IDC_WATERLEFT                   1003
#define IDC_CR10_LIGHT_TIME             1003
#define IDC_CR10_LIGHT_TIME_ON          1003
#define IDC_CAMERA1                     1004
#define IDC_ENAME                       1004
#define IDC_AIRP                        1004
#define IDC_PUMPED                      1004
#define IDC_CR10_LIGHT_TIME_OFF         1004
#define IDC_N_LOCATIONS                 1005
#define IDC_CAMERA2                     1005
#define IDC_FANN                        1005
#define IDC_LEFT                        1005
#define IDC_LIST1                       1005
#define IDC_NEW_M_LEVEL                 1005
#define IDC_SELECT_ALLI                 1006
#define IDC_LIGHTN                      1006
#define ID_AUTOSTART                    1006
#define IDC_NEW_FAN_TIME                1006
#define IDC_SELECT_ALLS                 1007
#define IDC_WATERN                      1007
#define IDC_NEW_LIGHT_TIME              1007
#define IDC_NEXTBURST                   1007
#define IDC_NEW_LIGHT_TIME_ON           1007
#define IDC_SPIN1                       1008
#define IDC_AIRN                        1008
#define IDC_CAMERA_INTERVAL             1008
#define IDC_NEW_LIGHT_TIME_OFF          1008
#define IDC_TVALUE                      1009
#define IDC_UNDO                        1009
#define IDC_SPIN2                       1009
#define IDC_SAVE                        1010
#define IDC_DATA_FOLDER                 1011
#define IDC_CLEAR                       1011
#define IDC_LOCATION_LIST               1012
#define IDC_PICTURE                     1012
#define IDC_SAVE_PROJECT                1013
#define IDC_DATA_RETRIEVAL_FREQ         1014
#define IDC_GRAPH_PLOT_FREQ             1015
#define IDC_SAVE_DATA_FREQ              1016
#define IDC_N_BACK_POINTS               1017
#define IDC_NEW_ILFILE_FREQ             1018
#define IDC_VISIBLE_SPAN                1019
#define IDC_NEW_FSFILE_FREQ             1020
#define IDC_N_GRAPHS                    1021
#define IDC_WHICH_GRAPH                 1022
#define IDC_EDITLIST                    1023
#define IDC_CONNECTED                   1036
#define IDC_OPMODE                      1037
#define IDC_CR10TIME                    1038
#define IDC_DATETIMEPICKER1             1040
#define IDC_DATETIMEPICKER2             1041
#define IDC_ABOUT_TEXT_1                1042
#define IDC_ABOUT_TEXT_2                1043
#define IDC_ABOUT_TEXT_3                1044
#define IDC_ABOUT_TEXT_4                1045
#define IDC_BUTTON1                     1051
#define IDC_CONNECT                     1051
#define IDC_CREATENEWGROUP              1051
#define IDC_UPLOADPROGRAM               1051
#define IDC_SETTINGS                    1051
#define IDC_PAUSE                       1051
#define IDC_IMPORT_FSL                  1051
#define IDC_CR10_FUNCTIONS              1051
#define IDC_DELETE_GRAPH                1051
#define IDC_BUTTON2                     1052
#define IDC_UPLOAD_PROGRAM              1052
#define IDC_UPDATE_TIME                 1052
#define IDC_FLAGS                       1052
#define IDC_CAMERAB                     1052
#define IDC_BUTTON3                     1053
#define IDC_SWITCH_MODE                 1053
#define IDC_GET_FINAL_STORAGE           1053
#define IDC_NEW                         1053
#define IDC_BUTTON4                     1054
#define IDC_CHANGE_TIME                 1054
#define IDC_SETLOCATION                 1054
#define IDC_GET_FS                      1054
#define IDC_DELETE                      1054
#define IDC_BUTTON5                     1055
#define IDC_DATA_COLLECTION             1055
#define IDC_UNLOCK_PASSWORD             1055
#define IDC_BUTTON6                     1056
#define IDC_VIEWHISTORY                 1056
#define IDC_SET_FLAGS                   1056
#define IDC_INITIALIZATION              1056
#define IDC_BUTTON7                     1057
#define IDC_CALIBRATION                 1057
#define IDC_BUTTON8                     1058
#define IDC_BUTTON9                     1059
#define IDC_BUTTON10                    1060
#define IDC_RESET_FINAL_STORAGE         1060
#define IDC_BUTTON11                    1061
#define IDC_BUTTON12                    1062
#define IDC_SET_INPUT_LOC               1062
#define IDC_TIMEWIN                     1070
#define IDC_EDIT1                       1072
#define IDC_EDIT2                       1073
#define IDC_EDIT3                       1074
#define IDC_TIMEWIN1                    1075
#define IDC_GETVALUE                    1075
#define IDC_CV4                         1075
#define IDC_VALUE                       1075
#define IDC_TIMEWIN2                    1076
#define IDC_SETVALUE                    1076
#define IDC_CV5                         1076
#define IDC_TIMEWIN3                    1077
#define IDC_CV6                         1077
#define IDC_TIMEWIN4                    1078
#define IDC_UV1                         1078
#define IDC_TIMEWIN5                    1079
#define IDC_UV2                         1079
#define IDC_TIMEWIN6                    1080
#define IDC_UV3                         1080
#define IDC_UV4                         1081
#define IDC_EDITDELAY                   1082
#define IDC_UV5                         1082
#define IDC_TW1                         1083
#define IDC_UV6                         1083
#define IDC_RETR_TIME                   1084
#define IDC_DATA_PLOT_FREQ              1085
#define IDC_ALL_FILES                   1085
#define IDC_NPOINTS                     1086
#define IDC_TW2                         1086
#define IDC_NEW_FILES_ONLY              1086
#define IDC_VIS_TIME_SPAN               1087
#define IDC_TW3                         1087
#define IDC_REAL_TIME_FILES             1087
#define IDC_C_WGRAPH                    1088
#define IDC_JTIME                       1088
#define IDC_NUM_SELECTED                1088
#define IDC_ACTIVE_LIST                 1089
#define IDC_JTIMEMAX                    1089
#define IDC_SET_DEFAULT                 1089
#define IDC_SHOW_GRAPH                  1090
#define IDC_KTIME                       1090
#define IDC_DIAGNOSTIC                  1090
#define IDC_HISTORY_FILES               1090
#define IDC_ERROR_FILES                 1091
#define IDC_EDIT_LIST                   1091
#define IDC_KTIMEMAX                    1091
#define IDC_OTIME                       1092
#define IDC_PICTURE_FILES               1092
#define IDC_OTIMEMAX                    1093
#define IDC_SOURCE_FOLDER               1093
#define IDC_DESTINATION_FOLDER          1094
#define IDC_SELECT_FILES                1095
#define IDC_ARCHIVE_FILES               1096
#define IDC_FLOPPY                      1097
#define IDC_PCMCIA                      1098
#define IDC_OTHER                       1099
#define IDC_FSL_FILE                    1100
#define IDC_A_LOCATIONS                 1101
#define IDC_S_LOCATIONS                 1102
#define IDC_F                           1102
#define IDC_RENAME_LOCATION             1103
#define IDC_SORT_LOCATIONS              1104
#define IDC_INSERT                      1105
#define IDC_REMOVE                      1106
#define IDC_FILELIST                    1106
#define IDC_TOTAL_BYTES                 1107
#define IDC_JPG                         1108
#define IDC_DIB                         1109
#define IDC_DIBTOJPG                    1112
#define IDC_EDIT4                       1115
#define IDC_FSGROUP_NAME                1115
#define IDC_EWETUPTIME                  1115
#define IDC_C_LAST                      1115
#define IDC_AVG_TIME                    1115
#define IDC_FSGROUP_NAME2               1116
#define IDC_N_FSFILES                   1116
#define IDC_TOBESERVICED                1116
#define IDC_EDIT5                       1117
#define IDC_WILFILE                     1117
#define IDC_C_NEXT                      1117
#define IDC_EDIT6                       1118
#define IDC_NIL                         1118
#define IDC_C_FREQUENCY                 1118
#define IDC_EDIT7                       1119
#define IDC_NFS                         1119
#define IDC_ILGROUPNAME                 1120
#define IDC_WILFILE2                    1121
#define IDC_WFSFILE                     1121
#define IDC_NILFILES                    1123
#define IDC_MIN_VALUE                   1124
#define IDC_MAX_VALUE                   1125
#define IDC_SAVE_DATA                   1129
#define IDC_MAX                         1131
#define IDC_MIN                         1132
#define IDC_GROUP                       1133
#define IDC_CHAMBER1                    1150
#define IDC_CHAMBER2                    1151
#define IDC_MTIME                       1152
#define IDC_FANS                        1153
#define IDC_MTIME2                      1153
#define IDC_LIGHTS                      1154
#define IDC_WATERF                      1155
#define IDC_WATERB                      1156
#define IDC_APUMP                       1157
#define IDC_CHECKOUT                    1158
#define IDC_BACKCOLOR                   1159
#define IDC_CV1                         1161
#define IDC_CV2                         1162
#define IDC_CV3                         1163
#define IDC_CV7                         1166
#define IDC_NEW_NAME                    1170
#define IDC_OLD_NAME                    1172
#define IDC_UV7                         1172
#define IDC_NUMBER                      1173
#define IDC_CV9                         1173
#define IDC_CV10                        1174
#define IDC_CV11                        1175
#define IDC_CV12                        1176
#define IDC_CV13                        1177
#define IDC_CV14                        1178
#define IDC_UV9                         1179
#define IDC_UV10                        1180
#define IDC_UV11                        1181
#define IDC_UV12                        1182
#define IDC_UV8                         1183
#define IDC_UV13                        1184
#define IDC_CV8                         1185
#define IDC_VPBURST                     1186
#define IDC_UV14                        1186
#define IDC_PROGRESS1                   1187
#define IDC_EBURSTLENGTH                1187
#define IDC_WINDOW_TEXT                 1188
#define IDC_FBURST                      1188
#define IDC_PERCENT                     1189
#define IDC_VTOPUMP                     1189
#define IDC_TOTAL_PUMPED                1190
#define IDC_TIME                        1192
#define IDC_HISTORYLIST                 1193
#define IDC_TIME2                       1193
#define IDC_SELECT_CHAMBER              1194
#define IDC_COMMENTS                    1194
#define IDC_VIEW_CR10_DIAGNOSTIC        1195
#define IDC_SMP_FREQ                    1195
#define IDC_CR10_TIME                   1196
#define IDC_COMPUTER_TIME               1197
#define IDC_WETUP_INVERVAL              1198
#define IDC_WETUP_INTERVAL              1198
#define IDC_DATA_TRANSFER               1200
#define IDC_COMPUTER_CONTROLLED         1200
#define IDC_CAMERAS                     1201
#define IDC_TEXT_LIGHTS                 1201
#define IDC_TEXT_LIGHTS_ON              1201
#define IDC_CHANGE_LANGUAGE             1202
#define IDC_TEXT_FANS                   1202
#define IDC_GRAPH                       1203
#define IDC_TEXT_MOISTURE               1203
#define IDC_SYSTEM_CHECK                1204
#define IDC_WETUPTEXT                   1204
#define IDC_TEXT_LIGHTS_OFF             1204
#define IDC_MAN_SAMPLE                  1205
#define IDC_WMINUTES                    1205
#define IDC_LAST_SMP_AVERAGE            1205
#define IDC_SYSTEM_CONTROLS             1206
#define IDC_DISPLAYBOX                  1206
#define IDC_HELP_BUTTON                 1207
#define IDC_HISTORY                     1208
#define IDC_ERRORS                      1209
#define IDC_EXIT                        1210
#define IDC_WETUP_SETTINGS              1210
#define IDC_AUTO_WRAP                   1211
#define IDC_CONTROL_MODE                1212
#define IDC_MODE_TEXT                   1213
#define IDC_MICON                       1214
#define IDC_MILITARY_TIME               1215
#define IDC_OLDNAME                     1216
#define IDC_ARRAY_ID                    1217
#define IDC_NEWNAME                     1217
#define IDC_HOURS                       1218
#define IDC_LAST_FAIL_CODE              1218
#define IDC_MINUTES                     1219
#define IDC_N_RETRIEVED                 1219
#define IDC_W_FLAG                      1221
#define IDC_FLAG_STATE                  1222
#define IDC_REPICTURE                   1223
#define IDC_G_TIME                      1224
#define IDC_G_VALUE                     1225
#define IDC_GRAPH_DATA                  1230
#define IDC_GRAPH_TIME                  1231
#define IDC_GRAPH_VALUE                 1232
#define IDC_WIN_TEXT                    1235
#define IDC_COMBO1                      1236
#define IDC_FS_FREQUENCY                1236
#define IDC_ERROR_COUNT                 1236
#define IDC_W_CAMERA                    1236
#define IDC_W_GROUP                     1236
#define IDC_READS                       1237
#define IDC_COMBO3                      1238
#define IDC_W_CHAMBER                   1238
#define IDC_LIST2                       1239
#define IDC_INPUT_LOCATIONS             1239
#define IDD_LADADIAG_DIALOG             1240
#define IDC_FS_LAST                     1240
#define IDC_DIAGNOSTICLIST              1241
#define IDC_FS_NEXT                     1241
#define IDC_START                       1242
#define IDC_FS_REMAINING                1242
#define IDC_FS_LIST                     1243
#define IDC_START2                      1243
#define IDC_NEW_FS_FILE                 1245
#define IDC_TEXT                        1249
#define IDC_TEXT31                      1249
#define IDD_LADASETUP_DIALOG            1250
#define IDC_TEXT39                      1250
#define ID_NEXT                         1251
#define IDD_SYSTEMDIAG_DIALOG           1251
#define IDC_TEXT47                      1251
#define ID_BACK                         1252
#define IDD_GROUP_PROPERTIES            1252
#define IDC_TEXT43                      1252
#define IDC_STEP                        1253
#define IDD_PARAM_DIALOG                1253
#define IDC_CAMERAA                     1253
#define IDC_TITLE                       1254
#define IDD_WETUP_DIALOG                1254
#define IDC_CHAMBER_A                   1254
#define IDC_CHECK1                      1255
#define IDD_YESNOCANCEL                 1255
#define IDC_CHAMBER_B                   1255
#define IDC_CHECK2                      1256
#define IDD_OKCANCEL                    1256
#define IDC_DISPLAY_WINDOW              1256
#define IDC_CHECK3                      1257
#define IDD_ABORTRETRYIGNORE            1257
#define IDC_STEPPROP                    1257
#define IDC_CHECK4                      1258
#define IDD_NEW_PROJECT1                1258
#define IDC_START1                      1258
#define IDC_CHECK5                      1259
#define IDD_NEW_PROJECT2                1259
#define IDC_MTIME1                      1259
#define IDC_CHECK6                      1260
#define IDD_CHECK_OUT                   1260
#define IDC_STEP1                       1260
#define IDC_CHECK7                      1261
#define IDD_MANUALTEST1                 1261
#define IDC_STEP2                       1261
#define IDC_CHECK8                      1262
#define IDC_TIME_REMAINING              1262
#define IDD_SHEET_DATA_COLLECTION       1262
#define IDC_CHECK9                      1263
#define IDC_TIME_ELAPSED                1263
#define IDD_PAGE_FINAL_STORAGE          1263
#define IDC_STEP_NUM                    1264
#define IDC_NEW_GRAPH                   1264
#define IDD_PAGE_INPUT_LOCATIONS        1264
#define IDC_GRAPH_NAME                  1265
#define IDD_PAGE_CAMERAS                1265
#define IDC_N_W_LOCATIONS               1266
#define IDD_DIALOG6                     1266
#define IDC_N_WETUP                     1267
#define IDD_PUMP_CHECK_2                1267
#define IDC_GRAPH_LIST                  1268
#define IDC_DOING                       1268
#define IDC_LOAD_VALIDATION             1269
#define IDC_C_OPTIONS                   1269
#define IDC_N_CAMERAS_TEXT              1270
#define IDC_N_CAMERAS                   1271
#define IDC_C_FREQ_TEXT                 1273
#define IDC_C_FREQ                      1274
#define IDC_ENABLE_CAMERA               1275
#define IDC_MESSAGE_TEXT                1276
#define IDC_TIME_ELAPSED_TEXT           1278
#define IDC_LAST_DSP                    1279
#define IDC_CR10_DSP                    1280
#define IDC_DO_FS                       1281
#define IDC_VALIDATE                    1281
#define IDC_N_ATTEMPTED                 1282
#define IDC_VALIDATE_ALL                1282
#define IDC_N_SUCCESSFUL                1283
#define IDC_TAB1                        1283
#define IDC_FILE_NAME                   1286
#define IDC_DATA_POINTS_TXT             1287
#define IDC_DATA_POINTS                 1288
#define IDC_LIGHTS1                     1289
#define IDC_LIGHTS2                     1290
#define IDC_READ_FREQ                   1291
#define IDC_NUM_READ                    1292
#define IDC_READS_DONE                  1293
#define IDC_READ_FAST                   1294
#define IDC_SERVICING                   1295
#define IDC_NAME                        1295
#define IDC_TOTALTIME                   1296
#define IDC_READING                     1296
#define IDC_RE_CALIBRATE                1297
#define IDB_JUNK                        1298
#define IDC_CALIBRATE                   1298
#define IDB_CR10FIVA                    1299
#define IDC_SENSORS                     1299
#define IDB_BITMAP1                     1300
#define IDC_LOAD_FILE                   1300
#define IDB_BITMAP2                     1301
#define IDC_PARAMS                      1301
#define IDB_BITMAP3                     1302
#define IDC_CHANGE_FREQ                 1302
#define IDB_BITMAP4                     1303
#define IDB_BIGREDBUTTON                1304
#define IDB_WETUP_INPROGRESS            1305
#define IDC_WRITE_FAST                  1305
#define IDC_WRITE_FREQ                  1306
#define IDC_WRITES_DONE                 1307
#define IDC_NO_FAILED                   1308
#define IDC_I_COMMAND                   1309
#define IDC_INPUT_LOCATION_LIST         1310
#define IDC_GRAPH_SIZE                  1310
#define IDC_UNITS                       1311
#define IDC_REFRESH                     1312
#define IDC_REFRESH_DATA_1              1313
#define IDC_AIR_TEMP                    1315
#define IDC_TEST_CAMERA                 1316
#define IDC_MAX_DOSAGE                  1317
#define IDC_CR10_MAX_DOSAGE             1318
#define IDC_NEW_MAX_DOSAGE              1319
#define IDC_DOSE_UNITS                  1320
#define IDC_TEXT1                       10050
#define IDC_TEXT2                       10051
#define IDC_TEXT3                       10052
#define IDC_TEXT4                       10053
#define IDC_TEXT5                       10054
#define IDC_TEXT6                       10055
#define IDC_TEXT7                       10056
#define IDC_TEXT8                       10057
#define IDC_TEXT9                       10058
#define IDC_TEXT10                      10059
#define IDC_TEXT11                      10060
#define IDC_TEXT12                      10061
#define IDC_TEXT13                      10062
#define IDC_TEXT14                      10063
#define IDC_TEXT15                      10064
#define IDC_TEXT16                      10065
#define IDC_TEXT17                      10066
#define IDC_TEXT18                      10067
#define IDC_TEXT19                      10068
#define IDC_TEXT20                      10069
#define IDC_TEXT21                      10070
#define IDC_TEXT22                      10071
#define IDC_TEXT23                      10072
#define IDC_TEXT24                      10073
#define IDC_TEXT25                      10074
#define IDC_TEXT26                      10075
#define IDC_TEXT27                      10076
#define IDC_AVERAGE                     10077
#define IDC_WSETTINGS                   10078
#define IDC_CHOOSE_ILL_LIST             10079
#define IDC_DOWETUP                     10080
#define IDC_FINISH                      10081
#define IDC_NEXT                        10082
#define IDC_ONE_INSTANT                 10083
#define IDC_BROWSE_DATA_FOLDER          10084
#define IDC_EDIT_LOCATION_LIST          10085
#define IDC_CHOOSE_FSL_LIST             10086
#define IDC_EDIT_WETUP_LOCATION_LIST    10086
#define IDC_SAVE_LOCATIONS              10087
#define IDC_SAVE_FINAL_STORAGE          10088
#define IDC_ASSOCIATEFSL                10089
#define IDC_BACK                        10090
#define IDS_MBUTTON1                    61446
#define IDS_MBUTTON2                    61447
#define IDS_MBUTTON3                    61448
#define IDS_MBUTTON4                    61449
#define IDS_MBUTTON5                    61450
#define IDS_MBUTTON6                    61451
#define IDS_MBUTTON7                    61452
#define IDS_MTITLE                      61455
#define IDS_MTEXT1                      61490
#define IDS_MTEXT2                      61491
#define IDS_MTEXT3                      61492
#define IDS_MTEXT4                      61493
#define IDS_LTEXT1                      61517
#define IDS_LTEXT2                      61518
#define IDS_LTEXT3                      61519
#define IDS_LTEXT4                      61520
#define IDS_LTEXT5                      61521
#define IDS_LTEXT6                      61522
#define IDS_LBUTTON1                    61526
#define IDS_LBUTTON2                    61527
#define IDS_LBUTTON3                    61528
#define IDS_LBUTTON4                    61529
#define IDS_CTITLE                      61530
#define IDS_CTEXT1                      61531
#define IDS_CTEXT2                      61532
#define IDS_CTEXT3                      61533
#define IDS_GTEXT1                      61536
#define IDS_GTEXT2                      61537
#define IDS_GTEXT3                      61538
#define IDS_GTEXT4                      61539
#define IDS_GTEXT5                      61540
#define IDS_GTEXT6                      61541
#define IDS_GTEXT7                      61542
#define IDS_GTEXT8                      61543
#define IDS_GBUTTON1                    61544
#define IDS_GBUTTON2                    61545
#define IDS_GBUTTON3                    61546
#define IDS_GTITLE                      61547
#define IDS_PROP_SHEET_TITLE            61548

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1321
#define _APS_NEXT_SYMED_VALUE           158
#endif
#endif
