//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CR10 Talk Resources.rc
//
#define IDC_BUTTON1                     3
#define IDC_BUTTON2                     4
#define IDC_BUTTON3                     5
#define IDC_BUTTON4                     6
#define IDC_BUTTON5                     7
#define IDC_BUTTON6                     8
#define IDC_BUTTON7                     9
#define IDC_BUTTON8                     10
#define IDD_DIALOG1                     101
#define MONITOR_DIALOG                  103
#define RENAME_LOCATION                 104
#define FLAGS_DIALOG                    105
#define PROGRESS_DIALOG                 107
#define IDC_CURSOR1                     108
#define IDC_CURSOR2                     109
#define IDR_MAINFRAME                   110
#define IDR_MAIN_FRAME                  111
#define IDD_EDIT_EVENT                  112
#define IDD_EDIT_CONDITION              113
#define IDD_NEW_EVENT                   114
#define IDD_EDIT_TEST                   115
#define IDD_DIALOG2                     116
#define IDD_DIALOG3                     117
#define IDD_CHOOSE_VARIABLE             118
#define IDD_PROGRAM_VARIABLES           119
#define IDD_CHOOSE_ITEM                 130
#define IDC_LOCATION1                   1000
#define IDC_LOCATION2                   1001
#define IDC_LOCATION3                   1002
#define IDC_COMBO1                      1002
#define IDC_LOCATION4                   1003
#define IDC_LOCATION5                   1004
#define IDC_LOCATION6                   1005
#define IDC_LOCATION7                   1006
#define IDC_LOCATION8                   1007
#define IDC_LOCATION9                   1008
#define IDC_LOCATION10                  1009
#define IDC_LOCATION11                  1010
#define IDC_LOCATION12                  1011
#define IDC_LOCATION13                  1012
#define IDC_LOCATION14                  1013
#define IDC_LOCATION15                  1014
#define IDC_IL_GB                       1015
#define IDC_LOC_1                       1016
#define IDC_LOC_2                       1017
#define IDC_LOC_3                       1018
#define IDC_LOC_4                       1019
#define IDC_LOC_5                       1020
#define IDC_LOC_6                       1021
#define IDC_LOC_7                       1022
#define IDC_LOC_8                       1023
#define IDC_LOC_9                       1024
#define IDC_LOC_10                      1025
#define IDC_LOC_11                      1026
#define IDC_LOC_12                      1027
#define IDC_LOC_13                      1028
#define IDC_LOC_14                      1029
#define IDC_LOC_15                      1030
#define IDC_U_FLAG1                     1040
#define IDC_U_FLAG3                     1041
#define IDC_U_FLAG2                     1042
#define IDC_U_FLAG4                     1043
#define IDC_U_FLAG5                     1044
#define IDC_U_FLAG6                     1045
#define IDC_U_FLAG7                     1046
#define IDC_U_FLAG8                     1047
#define IDC_UF_GB                       1048
#define IDC_UF_1                        1049
#define IDC_UF_2                        1050
#define IDC_UF_3                        1051
#define IDC_UF_4                        1052
#define IDC_UF_5                        1053
#define IDC_UF_6                        1054
#define IDC_UF_7                        1055
#define IDC_UF_8                        1056
#define IDC_P_FLAG1                     1060
#define IDC_P_FLAG3                     1061
#define IDC_P_FLAG2                     1062
#define IDC_P_FLAG4                     1063
#define IDC_P_FLAG5                     1064
#define IDC_P_FLAG6                     1065
#define IDC_P_FLAG7                     1066
#define IDC_P_FLAG8                     1067
#define IDC_PF_GB                       1068
#define IDC_PF_1                        1069
#define IDC_PF_2                        1070
#define IDC_PF_3                        1071
#define IDC_PF_4                        1072
#define IDC_PF_5                        1073
#define IDC_PF_6                        1074
#define IDC_PF_7                        1075
#define IDC_PF_8                        1076
#define IDC_TIMER1                      1080
#define IDC_TIMER2                      1081
#define IDC_TIMER3                      1082
#define IDC_TIMER4                      1083
#define IDC_TIMER5                      1084
#define IDC_TIMER6                      1085
#define IDC_TIMER7                      1086
#define IDC_T_GB                        1087
#define IDC_T_1                         1088
#define IDC_T_2                         1089
#define IDC_T_3                         1090
#define IDC_T_4                         1091
#define IDC_T_5                         1092
#define IDC_T_6                         1093
#define IDC_T_7                         1094
#define IDC_RECONNECTS                  1100
#define IDC_TIME_OUTS                   1101
#define IDC_WRITE_RETRIES               1102
#define IDC_WRITE_OPS                   1103
#define IDC_WCBUFF_REPEATS              1104
#define IDC_READ_BUF                    1105
#define IDC_LAST_READ_TIME              1106
#define IDC_RUN_TIME                    1107
#define IDC_SIGNATURE                   1108
#define IDC_LONGEST_DELAY               1109
#define IDC_LAST_DELAY                  1110
#define IDC_LOCATIONS_LEFT              1111
#define IDC_DMPTR                       1111
#define IDC_LOCS_RETRIEVE               1112
#define IDC_LASTDSP                     1113
#define IDC_DEBUG_GB                    1114
#define IDC_DBG_1                       1115
#define IDC_DBG_2                       1116
#define IDC_DBG_3                       1117
#define IDC_DBG_4                       1118
#define IDC_TTIME                       1118
#define IDC_DBG_5                       1119
#define IDC_RUNTIME_COUNTER             1119
#define IDC_DBG_6                       1120
#define IDC_DBG_7                       1121
#define IDC_DBG_8                       1122
#define IDC_DBG_9                       1123
#define IDC_DBG_10                      1124
#define IDC_DBG_11                      1125
#define IDC_DBG_12                      1126
#define IDC_DBG_13                      1127
#define IDC_DBG_14                      1128
#define IDC_DBG_15                      1129
#define IDC_DSP_LOCATION                1130
#define IDC_FS_LOCATIONS                1131
#define IDC_LOGGER_VER                  1132
#define IDC_MPTR_LOCATION               1133
#define IDC_NO_EO8S                     1134
#define IDC_NO_OVERRUN                  1135
#define IDC_NO_LOW_VOLT                 1136
#define IDC_CR10_MEMORY                 1137
#define IDC_BATT_VOLTAGE                1138
#define IDC_CR10_GB                     1139
#define IDC_CR_1                        1140
#define IDC_CR_2                        1141
#define IDC_CR_3                        1142
#define IDC_CR_4                        1143
#define IDC_CR_5                        1144
#define IDC_CR_6                        1145
#define IDC_CR_7                        1146
#define IDC_CR_8                        1147
#define IDC_CR_9                        1148
#define IDC_DBG_16                      1149
#define IDC_DBG_17                      1150
#define IDC_DLASTDSP                    1151
#define IDC_AVAILABLE_LOCATIONS_L       1155
#define IDC_SELECTED_LOCATIONS_L        1156
#define IDC_USER_FLAGS_C                1157
#define IDC_PORT_FLAGS_C                1158
#define IDC_CR10_TIME_C                 1159
#define IDC_CR10_INFO_C                 1160
#define IDC_INPUT_LOCATIONS_FREQ        1161
#define IDC_USER_FLAGS_FREQ             1162
#define IDC_SAVE_LOCATIONS_C            1162
#define IDC_PORT_FLAGS_FREQ             1163
#define IDC_CR10_TIME_FREQ              1164
#define IDC_CR10_INFO_FREQ              1165
#define IDC_INPUT_LOCATIONS_C           1166
#define IDC_INSERT_B                    1167
#define IDC_REMOVE_B                    1168
#define IDC_RENAME_B                    1169
#define IDC_NEW_NAME                    1170
#define IDC_SAVE_LOCATIONS_FREQ         1170
#define IDC_SORT_LOCATIONS              1171
#define IDC_OLD_NAME                    1172
#define IDC_LOCATION_NUMBER             1173
#define IDC_NUMBER                      1173
#define IDC_TIME                        1175
#define IDC_CR_TIME                     1176
#define IDC_EDIT_MPTR                   1179
#define IDC_MPTR_L                      1180
#define IDC_FS_POSITION                 1182
#define IDC_PROGRESS1                   1187
#define IDC_WINDOW_TEXT                 1188
#define IDC_PERCENT                     1189
#define IDC_RUSERFLAGS                  1190
#define IDC_RPORTFLAGS                  1191
#define IDC_CTOGGLEON                   1192
#define IDC_FLAGNAME1                   1193
#define IDC_FLAGNAME2                   1194
#define IDC_FLAGNAME3                   1195
#define IDC_FLAGNAME4                   1196
#define IDC_FLAGNAME5                   1197
#define IDC_FLAGNAME6                   1198
#define IDC_FLAGNAME7                   1199
#define IDC_FLAGNAME8                   1200
#define IDC_FSTATUS1                    1201
#define IDC_FSTATUS2                    1202
#define IDC_FSTATUS3                    1203
#define IDC_FSTATUS4                    1204
#define IDC_FSTATUS5                    1205
#define IDC_FSTATUS6                    1206
#define IDC_FSTATUS7                    1207
#define IDC_FSTATUS8                    1208
#define IDC_R1                          1209
#define IDC_R2                          1210
#define IDC_R3                          1211
#define IDC_R4                          1212
#define IDC_R5                          1213
#define IDC_R6                          1214
#define IDC_R7                          1215
#define IDC_R8                          1216
#define IDC_RE1                         1217
#define IDC_RE2                         1218
#define IDC_RE3                         1219
#define IDC_RE4                         1220
#define IDC_RE5                         1221
#define IDC_RE6                         1222
#define IDC_RE7                         1223
#define IDC_RE8                         1224
#define IDC_FLAGFREQ1                   1225
#define IDC_FLAGFREQ2                   1226
#define IDC_FLAGFREQ3                   1227
#define IDC_FLAGFREQ4                   1228
#define IDC_FLAGFREQ5                   1229
#define IDC_FLAGFREQ6                   1230
#define IDC_FLAGFREQ7                   1231
#define IDC_FLAGFREQ8                   1232
#define IDC_WIN_TEXT                    1235
#define IDC_TEMP_EDIT                   1236
#define IDC_FSL_FILE                    1244
#define IDC_SEDIT                       1250
#define IDC_STEXT1                      1251
#define IDC_STEXT2                      1252
#define IDC_STEXT3                      1253
#define IDC_MTEXT1                      1254
#define IDC_LTEXT1                      1255
#define IDC_SAVE_FS                     1256
#define IDC_CONDITIONAL_LIST            1258
#define IDC_CONTROL_LIST                1259
#define IDC_EVENT_TITLE                 1261
#define IDC_NEW_EVENT                   1262
#define IDC_NEW_STATEMENT               1263
#define IDC_DELETE_STATEMENT            1264
#define IDC_NEW_TEST                    1265
#define IDC_DELETE_TEST                 1266
#define IDC_EVENT_NUMBER                1267
#define IDC_EDIT_STATEMENT              1268
#define IDC_VARIABLE                    1269
#define IDC_EDIT_TEST                   1269
#define IDC_CONDITIONAL_STATEMENT       1270
#define IDC_EVENT_FREQUENCY             1270
#define IDC_BUTTON9                     1274
#define IDC_ITEM_LIST                   1275
#define IDC_BUTTON10                    1275
#define IDC_SPIN1                       1277
#define IDC_INSERT                      1278
#define IDC_DELETE                      1279
#define IDC_DIRECTION_TEXT              1280
#define IDC_EDIT_NUMBER                 1282
#define IDC_RENAME_EVENT                1285
#define IDC_VALUE                       1286
#define IDC_EVALUATE                    1287
#define IDC_RENAME_STATEMENT            1288
#define IDC_EDIT1                       1289
#define IDC_EXPRESSION_LIST             1290
#define IDC_VVALUE                      1290
#define IDC_TEST                        1292
#define IDC_CHOICES                     1293
#define IDC_ITEMS                       1294
#define IDC_TESTS                       1295
#define IDC_TEST_TEXT                   1296
#define IDC_FULL_EXPRESSION             1298
#define IDC_LIST1                       1299
#define IDC_NUM_SELECTED                1300
#define IDC_RADIO1                      1301
#define IDC_RADIO2                      1302
#define IDC_PROG_VAR                    1303
#define IDC_NEW                         1304
#define IDC_EDIT                        1305
#define IDC_EVENT_VAR                   1306
#define IDC_EVENT                       1307
#define IDC_RADIO3                      1308
#define IDC_VAR_VALUE                   1309
#define IDC_CONST_VAR                   1310
#define IDC_VAR_VALUE_TEXT              1311
#define IDC_PROGRAM_VARIABLES           1312
#define IDC_RUN_EVENT                   1313
#define IDC_TEST_NUM                    1314
#define IDC_READONLY                    1315
#define IDC_ARRAY                       1316
#define IDC_NELEMENTS                   1317
#define IDC_VNAME                       1318
#define IDC_ADD                         1319
#define IDC_VLIST                       1320

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1321
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
