#if !defined(AFX_PVALARM_H__6C724981_F12D_11D3_9DC7_00A0CC3A1AD6__INCLUDED_)
#define AFX_PVALARM_H__6C724981_F12D_11D3_9DC7_00A0CC3A1AD6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPVAlarm wrapper class

class CPVAlarm : public COleDispatchDriver
{
public:
	CPVAlarm() {}		// Calls COleDispatchDriver default constructor
	CPVAlarm(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPVAlarm(const CPVAlarm& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	short GetRepeat();
	void SetRepeat(short nNewValue);
	CString GetDescription();
	void SetDescription(LPCTSTR lpszNewValue);
	BOOL GetOn();
	void SetOn(BOOL bNewValue);
	CString GetDisplay();
	void SetDisplay(LPCTSTR lpszNewValue);
	DATE GetStartDateTime();
	void SetStartDateTime(DATE newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PVALARM_H__6C724981_F12D_11D3_9DC7_00A0CC3A1AD6__INCLUDED_)
