#if !defined(AFX_PVAPPOINTMENT_H__6C724985_F12D_11D3_9DC7_00A0CC3A1AD6__INCLUDED_)
#define AFX_PVAPPOINTMENT_H__6C724985_F12D_11D3_9DC7_00A0CC3A1AD6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPVAlarm;

/////////////////////////////////////////////////////////////////////////////
// CPVAppointment wrapper class

class CPVAppointment : public COleDispatchDriver
{
public:
	CPVAppointment() {}		// Calls COleDispatchDriver default constructor
	CPVAppointment(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPVAppointment(const CPVAppointment& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	DATE GetStartDateTime();
	void SetStartDateTime(DATE newValue);
	DATE GetEndDateTime();
	void SetEndDateTime(DATE newValue);
	CString GetDescription();
	void SetDescription(LPCTSTR lpszNewValue);
	CPVAlarm GetAlarm();
	void SetAlarm(LPDISPATCH newValue);
	VARIANT GetDataVariant();
	void SetDataVariant(const VARIANT& newValue);
	long GetKey();
	BOOL GetReadOnly();
	void SetReadOnly(BOOL bNewValue);
	void BeginAppointmentEdit();
	void EndAppointmentEdit();
	BOOL GetSelected();
	void SetSelected(BOOL bNewValue);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long newValue);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long newValue);
	unsigned long GetBarColor();
	void SetBarColor(unsigned long newValue);
	CString GetExecuteProgram();
	void SetExecuteProgram(LPCTSTR lpszNewValue);
	CString GetExecuteParameters();
	void SetExecuteParameters(LPCTSTR lpszNewValue);
	void Execute(long Option);
	void DisplayAppointmentDialog();
	void CloseAppointmentDialog(long Option);
	BOOL GetAllDayEvent();
	void SetAllDayEvent(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PVAPPOINTMENT_H__6C724985_F12D_11D3_9DC7_00A0CC3A1AD6__INCLUDED_)
