#if !defined(AFX_PVAPPOINTMENTSET_H__6C724982_F12D_11D3_9DC7_00A0CC3A1AD6__INCLUDED_)
#define AFX_PVAPPOINTMENTSET_H__6C724982_F12D_11D3_9DC7_00A0CC3A1AD6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPVAppointment;

/////////////////////////////////////////////////////////////////////////////
// CPVAppointmentSet wrapper class

class CPVAppointmentSet : public COleDispatchDriver
{
public:
	CPVAppointmentSet() {}		// Calls COleDispatchDriver default constructor
	CPVAppointmentSet(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPVAppointmentSet(const CPVAppointmentSet& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CPVAppointment Add(LPCTSTR Description, DATE StartDateTime, DATE EndDateTime);
	CPVAppointment Get(DATE Date);
	void Remove(long Key);
	long GetCountAt(DATE Date);
	CPVAppointment GetNext(LPDISPATCH CurrentAppointment);
	CPVAppointment GetPrevious(LPDISPATCH CurrentAppointment);
	CPVAppointment GetAppointmentAtPoint(long x, long y);
	CPVAppointment GetSelectedAppointment();
	void Reset();
	CPVAppointment GetFirst();
	CPVAppointment GetLast();
	long GetCountInRange(DATE StartDate, DATE EndDate);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PVAPPOINTMENTSET_H__6C724982_F12D_11D3_9DC7_00A0CC3A1AD6__INCLUDED_)
