#if !defined(AFX_PVTASKPAD_H__2E6661B9_5986_11D3_9CE3_00A0CC3A1AD6__INCLUDED_)
#define AFX_PVTASKPAD_H__2E6661B9_5986_11D3_9CE3_00A0CC3A1AD6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPVTaskItem;
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CPVTaskPad wrapper class

class CPVTaskPad : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPVTaskPad)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xe56f52b0, 0xd0ad, 0x11d2, { 0x9c, 0xa, 0x0, 0xa0, 0xcc, 0x3a, 0x1a, 0xd6 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CPVTaskItem Get_Item(long Index);
	COleFont GetHeaderFont();
	void SetHeaderFont(LPDISPATCH newValue);
	void SetRefHeaderFont(LPDISPATCH newValue);
	COleFont GetTasksFont();
	void SetTasksFont(LPDISPATCH newValue);
	void SetRefTasksFont(LPDISPATCH newValue);
	CPVTaskItem AddItem(BOOL bComplete, LPCTSTR Description, DATE DueDate);
	long RemoveItem(long Index);
	CPVTaskItem GetItem(long Index);
	short GetCompletionStyle();
	void SetCompletionStyle(short nNewValue);
	short GetBorderStyle();
	void SetBorderStyle(short nNewValue);
	short GetAppearance();
	void SetAppearance(short nNewValue);
	void CancelEvent();
	void Reset();
	long GetCount();
	unsigned long GetOverdueColor();
	void SetOverdueColor(unsigned long newValue);
	unsigned long GetDefaultItemForeColor();
	void SetDefaultItemForeColor(unsigned long newValue);
	BOOL GetRedraw();
	void SetRedraw(BOOL bNewValue);
	long GetHwndEdit();
	long GetHwndPopupMenu();
	BOOL GetHidden(LPCTSTR Field);
	void SetHidden(LPCTSTR Field, BOOL bNewValue);
	long GetSelectMode();
	void SetSelectMode(long nNewValue);
	long GetSelectedCount();
	BOOL Load(LPCTSTR FileName, long Options);
	BOOL Save(LPCTSTR FileName, long Options);
	CString GetFieldHeading(LPCTSTR Field);
	void SetFieldHeading(LPCTSTR Field, LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PVTASKPAD_H__2E6661B9_5986_11D3_9CE3_00A0CC3A1AD6__INCLUDED_)
