#if !defined(AFX_PVTASKITEM_H__2E6661B8_5986_11D3_9CE3_00A0CC3A1AD6__INCLUDED_)
#define AFX_PVTASKITEM_H__2E6661B8_5986_11D3_9CE3_00A0CC3A1AD6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPVTaskItem wrapper class

class CPVTaskItem : public COleDispatchDriver
{
public:
	CPVTaskItem() {}		// Calls COleDispatchDriver default constructor
	CPVTaskItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPVTaskItem(const CPVTaskItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetIndex();
	unsigned long GetForeColor();
	void SetForeColor(unsigned long newValue);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long newValue);
	VARIANT GetFieldValue(LPCTSTR Field);
	void SetFieldValue(LPCTSTR Field, const VARIANT& newValue);
	BOOL GetSelected();
	void SetSelected(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PVTASKITEM_H__2E6661B8_5986_11D3_9CE3_00A0CC3A1AD6__INCLUDED_)
