//  Mark Salisbury
//  529-71-8265
//  2nd hour
//  Problems for Sequential Algorithms #2
//  This program performs ops. on integers

#include <iostream.h>

void main() {
int IntOne = 0;
int IntTwo = 0;
cout << "Enter integer #1: " << flush;
cin >> IntOne;
cout << "Enter integer #2: " << flush;
cin >> IntTwo;
cout << "Their difference is: " << (IntOne - IntTwo) <<endl;
cout << "Their product is: " << (IntOne * IntTwo) << endl;
cout << "Their quotient is: " << (IntOne / IntTwo) << endl;
}
