//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LADA Control Module.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_GRAPHBUTTONFORM_TMPL        100
#define IDD_LADACONTROLMODULE_FORM      101
#define IDS_DATA_TRANSFER               101
#define IDD_GRAPHBUTTONFORM_FORM        102
#define IDS_GRAPH                       102
#define IDS_CAMERAS                     103
#define RENAME_LOCATION                 104
#define IDS_SYSTEM_CHECK                104
#define IDS_CHANGE_LANGUAGE             105
#define IDS_MAN_SAMPLE                  106
#define IDS_SYS_DIAGNOSIS               107
#define PROGRESS_DIALOG                 107
#define IDS_STEXT1                      108
#define IDS_STEXT2                      109
#define IDS_STEXT3                      110
#define IDS_STEXT4                      111
#define IDS_STEXT5                      112
#define IDS_STEXT6                      113
#define IDS_STEXT7                      114
#define IDS_SBUTTON1                    115
#define IDS_SBUTTON2                    116
#define IDS_SBUTTON3                    117
#define IDS_SBUTTON4                    118
#define IDS_SBUTTON5                    119
#define IDC_HELPTEXT1                   120
#define IDS_SBUTTON6                    120
#define IDC_HELPTEXT2                   121
#define IDS_SBUTTON7                    121
#define IDC_HELPTEXT3                   122
#define IDS_SBUTTON8                    122
#define IDC_HELPTEXT4                   123
#define IDS_STITLE                      123
#define IDC_HELPTEXT5                   124
#define IDS_WELCOMESTRING               124
#define IDC_HELPTEXT6                   125
#define IDC_HELPTEXT7                   126
#define IDC_WELCOMETEXT                 127
#define IDR_MAINFRAME                   128
#define ID_SETUP                        128
#define IDR_LADATYPE                    129
#define MONITOR_DIALOG                  129
#define ID_CHECK_OUT                    129
#define ID_WET_UP                       130
#define IDD_CHOOSE_TIME                 131
#define ID_NORMAL                       131
#define ID_DIAGNOSTICS                  132
#define IDD_NEW_PROJECT                 133
#define IDB_HOTTOOLBAR                  133
#define ID_CHANGE_LANGUAGE              133
#define IDB_COLDTOOLBAR                 134
#define ID_EXIT                         134
#define IDC_TEMP_FILEVIEW               135
#define IDB_NCONNECTED                  140
#define IDB_CONNECTED                   141
#define IDB_HOTTOOR                     145
#define IDC_FIRST_CHECKBOX              150
#define IDD_DIALOG1                     150
#define IDD_GRAPH_PROPERTIES            150
#define IDD_CAMERADIALOG_DIALOG         151
#define IDB_PROGRAMBMP                  156
#define IDB_CHECKBOXES                  157
#define IDD_EDITLOCATION                158
#define IDD_DIALOG2                     159
#define IDD_DATA_TRANSFER               164
#define IDD_SELECTICON                  178
#define IDC_LAST_CHECKBOX               200
#define IDC_FIRSTNUMBERBOX              201
#define IDC_FREQUENCY                   1000
#define IDC_RESOLUTION                  1001
#define IDC_AUTOWRAP                    1002
#define IDC_FILEBOX                     1003
#define IDC_CAMERA1                     1004
#define IDC_N_LOCATIONS                 1005
#define IDC_CAMERA2                     1005
#define IDC_SELECT_ALLI                 1006
#define IDC_SELECT_ALLS                 1007
#define IDC_SPIN1                       1008
#define IDC_TVALUE                      1009
#define IDC_SAVE                        1010
#define IDC_DATA_FOLDER                 1011
#define IDC_CLEAR                       1011
#define IDC_LOCATION_LIST               1012
#define IDC_PICTURE                     1012
#define IDC_SAVE_PROJECT                1013
#define IDC_DATA_RETRIEVAL_FREQ         1014
#define IDC_GRAPH_PLOT_FREQ             1015
#define IDC_SAVE_DATA_FREQ              1016
#define IDC_N_BACK_POINTS               1017
#define IDC_SIZE_TIME                   1018
#define IDC_VISIBLE_SPAN                1019
#define IDC_SAVE_LOCATIONS_TEXT         1020
#define IDC_N_GRAPHS                    1021
#define IDC_WHICH_GRAPH                 1022
#define IDC_EDITLIST                    1023
#define IDC_EDIT_LOCATION_LIST          1024
#define IDC_SAVE_LOCATIONS              1025
#define IDC_AVERAGE                     1026
#define IDC_ONE_INSTANT                 1027
#define IDC_SAVE_FINAL_STORAGE          1028
#define IDC_BY_TIME                     1029
#define IDC_BY_SIZE                     1030
#define IDC_BROWSE_DATA_FOLDER          1031
#define IDS_ABOUT_TEXT_1                1032
#define IDS_ABOUT_TEXT_2                1033
#define IDS_ABOUT_TEXT_3                1034
#define IDS_ABOUT_TEXT_4                1035
#define IDC_CONNECTED                   1036
#define IDC_CR10TIME                    1038
#define IDC_DATETIMEPICKER1             1040
#define IDC_DATETIMEPICKER2             1041
#define IDC_ABOUT_TEXT_1                1042
#define IDC_ABOUT_TEXT_2                1043
#define IDC_ABOUT_TEXT_3                1044
#define IDC_ABOUT_TEXT_4                1045
#define IDS_OK                          1046
#define IDS_CANCEL                      1047
#define IDS_ABOUT_TITLE                 1048
#define IDC_TEXT1                       1050
#define IDC_TEXT2                       1051
#define IDC_TEXT3                       1052
#define IDC_TEXT4                       1053
#define IDC_TEXT5                       1054
#define IDC_TEXT6                       1055
#define IDC_TEXT7                       1056
#define IDC_TEXT8                       1057
#define IDC_TEXT9                       1058
#define IDC_TEXT10                      1059
#define IDC_TEXT11                      1060
#define IDC_TEXT12                      1061
#define IDC_TEXT13                      1062
#define IDC_TEXT14                      1063
#define IDC_TEXT15                      1064
#define IDC_TEXT16                      1065
#define IDC_TEXT17                      1066
#define IDC_TIMEWIN                     1069
#define IDC_BUTTON1                     1070
#define IDC_EDIT1                       1070
#define IDC_BUTTON2                     1071
#define IDC_EDIT2                       1071
#define IDC_BUTTON3                     1072
#define IDC_EDIT3                       1072
#define IDC_BUTTON4                     1073
#define IDC_BUTTON5                     1074
#define IDC_BUTTON6                     1075
#define IDC_TIMEWIN1                    1075
#define IDC_GETVALUE                    1075
#define IDC_BUTTON7                     1076
#define IDC_TIMEWIN2                    1076
#define IDC_SETVALUE                    1076
#define IDC_BUTTON8                     1077
#define IDC_TIMEWIN3                    1077
#define IDC_BUTTON9                     1078
#define IDC_TIMEWIN4                    1078
#define IDC_BUTTON10                    1079
#define IDC_TIMEWIN5                    1079
#define IDC_BUTTON11                    1080
#define IDC_TIMEWIN6                    1080
#define IDC_BUTTON12                    1081
#define IDC_EDITDELAY                   1082
#define IDC_TW1                         1083
#define IDC_RETR_TIME                   1084
#define IDC_DATA_PLOT_FREQ              1085
#define IDC_ALL_FILES                   1085
#define IDC_NPOINTS                     1086
#define IDC_TW2                         1086
#define IDC_NEW_FILES_ONLY              1086
#define IDC_VIS_TIME_SPAN               1087
#define IDC_TW3                         1087
#define IDC_REAL_TIME_FILES             1087
#define IDC_C_WGRAPH                    1088
#define IDC_JTIME                       1088
#define IDC_NUM_SELECTED                1088
#define IDC_ACTIVE_LIST                 1089
#define IDC_JTIMEMAX                    1089
#define IDC_SET_DEFAULT                 1089
#define IDC_SHOW_GRAPH                  1090
#define IDC_KTIME                       1090
#define IDC_DIAGNOSTIC                  1090
#define IDC_EDIT_LIST                   1091
#define IDC_KTIMEMAX                    1091
#define IDC_BMPTOJPG                    1091
#define IDC_OTIME                       1092
#define IDC_PICTURE_FILES               1092
#define IDC_OTIMEMAX                    1093
#define IDC_SOURCE_FOLDER               1093
#define IDC_DESTINATION_FOLDER          1094
#define IDC_SELECT_FILES                1095
#define IDC_ARCHIVE_FILES               1096
#define IDC_FLOPPY                      1097
#define IDC_PCMCIA                      1098
#define IDC_OTHER                       1099
#define IDC_FSL_FILE                    1100
#define IDC_A_LOCATIONS                 1101
#define IDC_S_LOCATIONS                 1102
#define IDC_F                           1102
#define IDC_RENAME_LOCATION             1103
#define IDC_SORT_LOCATIONS              1104
#define IDC_INSERT                      1105
#define IDC_REMOVE                      1106
#define IDC_FILELIST                    1106
#define IDC_TOTAL_BYTES                 1107
#define IDC_JPG                         1108
#define IDC_DIB                         1109
#define IDC_DIBTOJPB                    1110
#define IDC_DIBTOJPG                    1112
#define IDC_NEW_NAME                    1170
#define IDC_OLD_NAME                    1172
#define IDC_NUMBER                      1173
#define IDC_PROGRESS1                   1187
#define IDC_WINDOW_TEXT                 1188
#define IDC_PERCENT                     1189
#define IDC_DATA_TRANSFER               1200
#define IDC_CAMERAS                     1201
#define IDC_CHANGE_LANGUAGE             1202
#define IDC_GRAPH                       1203
#define IDC_SYSTEM_CHECK                1204
#define IDC_MAN_SAMPLE                  1205
#define IDC_SYS_DIAGNOSIS               1206
#define IDC_WIN_TEXT                    1235
#define IDD_LADADIAG_DIALOG             1240
#define IDC_DIAGNOSTICLIST              1241
#define IDC_START                       1242
#define IDC_TEXT                        1249
#define IDD_LADASETUP_DIALOG            1250
#define ID_NEXT                         1251
#define ID_BACK                         1252
#define IDC_STEP                        1253
#define IDC_TITLE                       1254
#define IDC_CHECK1                      1255
#define IDC_CHECK2                      1256
#define IDC_CHECK3                      1257
#define IDC_CHECK4                      1258
#define IDC_CHECK5                      1259
#define IDC_CHECK6                      1260
#define IDC_CHECK7                      1261
#define IDC_CHECK8                      1262
#define IDC_CHECK9                      1263
#define IDB_JUNK                        1298
#define IDB_CR10FIVA                    1299
#define IDB_BITMAP1                     1300
#define IDB_BITMAP2                     1301
#define IDB_BITMAP3                     1302
#define IDB_BITMAP4                     1303
#define IDS_MBUTTON1                    61446
#define IDS_MBUTTON2                    61447
#define IDS_MBUTTON3                    61448
#define IDS_MBUTTON4                    61449
#define IDS_MBUTTON5                    61450
#define IDS_MBUTTON6                    61451
#define IDS_MBUTTON7                    61452
#define IDS_MTITLE                      61455
#define IDS_N_DATAPLOT1                 61456
#define IDS_N_DATAPLOT2                 61457
#define IDS_N_DATAPLOT3                 61458
#define IDS_N_DATAPLOT4                 61459
#define IDS_N_DATAPLOT5                 61460
#define IDS_N_DATAPLOT6                 61461
#define IDS_N_DATAPLOT7                 61462
#define IDS_N_BACKPOINT1                61463
#define IDS_N_BACKPOINT2                61464
#define IDS_N_BACKPOINT3                61465
#define IDS_N_BACKPOINT4                61466
#define IDS_N_DATARETR1                 61467
#define IDS_N_DATARETR2                 61468
#define IDS_N_DATARETR3                 61469
#define IDS_N_DATARETR4                 61470
#define IDS_N_DATARETR5                 61471
#define IDS_N_DATARETR6                 61472
#define IDS_N_DATARETR7                 61473
#define IDS_N_DATARETR8                 61474
#define IDS_N_DATARETR9                 61475
#define IDS_N_DATARETR10                61476
#define IDS_N_DATASAVE1                 61477
#define IDS_N_DATASAVE2                 61478
#define IDS_N_DATASAVE3                 61479
#define IDS_N_DATASAVE4                 61480
#define IDS_N_DATASAVE5                 61481
#define IDS_N_DATASAVE6                 61482
#define IDS_N_DATASAVE7                 61483
#define IDS_N_FILETIME1                 61484
#define IDS_N_FILETIME2                 61485
#define IDS_N_FILETIME3                 61486
#define IDS_N_FILESIZE1                 61487
#define IDS_N_FILESIZE2                 61488
#define IDS_N_FILESIZE3                 61489
#define IDS_MTEXT1                      61490
#define IDS_MTEXT2                      61491
#define IDS_MTEXT3                      61492
#define IDS_MTEXT4                      61493
#define IDS_PTITLE                      61494
#define IDS_PTEXT1                      61495
#define IDS_PTEXT2                      61496
#define IDS_PTEXT3                      61497
#define IDS_PTEXT4                      61498
#define IDS_PTEXT5                      61499
#define IDS_PTEXT6                      61500
#define IDS_PTEXT7                      61501
#define IDS_PTEXT8                      61502
#define IDS_PTEXT9                      61503
#define IDS_PTEXT10                     61504
#define IDS_PTEXT11                     61505
#define IDS_PTEXT12                     61506
#define IDS_PTEXT13                     61507
#define IDS_PTEXT14                     61508
#define IDS_PBUTTON1                    61509
#define IDS_PBUTTON2                    61510
#define IDS_PBUTTON3                    61511
#define IDS_PBUTTON4                    61512
#define IDS_PBUTTON5                    61513
#define IDS_PBUTTON6                    61514
#define IDS_PBUTTON7                    61515
#define IDS_PBUTTON8                    61516
#define IDS_LTEXT1                      61517
#define IDS_LTEXT2                      61518
#define IDS_LTEXT3                      61519
#define IDS_LTEXT4                      61520
#define IDS_LTEXT5                      61521
#define IDS_LTEXT6                      61522
#define IDS_LBUTTON1                    61526
#define IDS_LBUTTON2                    61527
#define IDS_LBUTTON3                    61528
#define IDS_LBUTTON4                    61529
#define IDS_CTITLE                      61530
#define IDS_CTEXT1                      61531
#define IDS_CTEXT2                      61532
#define IDS_CTEXT3                      61533
#define IDS_NOT_ENOUGH_DATA             61534
#define IDS_NO_ITEMS_SELECTED           61535
#define IDS_GTEXT1                      61536
#define IDS_GTEXT2                      61537
#define IDS_GTEXT3                      61538
#define IDS_GTEXT4                      61539
#define IDS_GTEXT5                      61540
#define IDS_GTEXT6                      61541
#define IDS_GTEXT7                      61542
#define IDS_GTEXT8                      61543
#define IDS_GBUTTON1                    61544
#define IDS_GBUTTON2                    61545
#define IDS_GBUTTON3                    61546
#define IDS_GTITLE                      61547

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           136
#endif
#endif
